import React from 'react'

const Football = () => {
    return (
        <div className='bg-dark-bg text-secondary-text'>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eum quasi quas debitis exercitationem voluptates quis sint dolorum id ad! Quae, magni doloremque reiciendis dolorum ducimus, eaque exercitationem modi quis sint iste obcaecati voluptatum quidem voluptas ipsa aliquam? Dignissimos reprehenderit, eaque labore quae, eligendi, molestias ipsa delectus sint tenetur odio mollitia enim earum corporis dolorum neque ipsam? Recusandae vero neque sunt nostrum quae optio quos tenetur repellendus fuga officia perferendis hic voluptatem atque, minima doloribus quia temporibus modi! Aspernatur blanditiis earum quia suscipit natus temporibus quasi sint eligendi totam animi nam facere ab maxime a repellat vitae autem, quod incidunt! Sint ex esse consequuntur laborum odit totam in dolor quam pariatur molestias recusandae animi ipsam dicta repellat modi libero impedit voluptate nihil, magni explicabo, similique consectetur obcaecati. Magni provident tempora quo suscipit neque! Quibusdam, animi dolores sed ducimus doloremque, aspernatur deleniti illum obcaecati est assumenda iste libero aliquid voluptatem laboriosam impedit molestias, at ipsum sint maiores dolore excepturi maxime. Voluptatem eius quam dignissimos aliquam mollitia, nihil beatae, ipsa dicta quisquam similique debitis voluptate accusantium quidem praesentium suscipit temporibus, asperiores saepe alias id provident dolorem et quis! Molestiae quam quis id voluptatibus labore tempore magni, eveniet, vitae sed excepturi, reprehenderit porro ipsam maiores amet esse! In architecto harum molestiae hic inventore pariatur earum iure sequi saepe porro perspiciatis, autem laboriosam rerum eos assumenda labore esse aliquam natus nesciunt officiis provident consequatur? Animi, culpa? Quas nulla saepe ab quam quae eaque, deleniti aliquid soluta maiores dignissimos repudiandae perspiciatis illum, consectetur a minus amet. Deleniti distinctio animi iusto qui dolores architecto magni, similique laboriosam recusandae molestias, impedit sequi. Dolor cum itaque quos? Reiciendis, hic laudantium? Pariatur numquam corrupti ratione est harum. Explicabo ipsam suscipit amet perferendis, nobis nemo sunt quia recusandae id tempore minima dolore, distinctio culpa sit adipisci rerum, nihil dignissimos nesciunt laudantium.
        </div>
    )
}

export default Football